Screen:
     
    MDTopAppBar:
        title: "Examen BFEEM"
        left_action_items: [["menu", lambda x: nav_drawer.set_state("open")]]

    MDNavigationLayout:
        ScreenManager:
            id: screen_manager

            # Définition des vues
            AccueilView:
            AproposView:
            ContactView:

        MDNavigationDrawer:
            id: nav_drawer
            radius: 0, dp(16), dp(16), 0

            Drawer:
                screen_manager: screen_manager
